### ISSUE TITLE
Reseervation Issues

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#1]
T-1 Reservation page @saikrishna20 
1. After selecting the date from calender- No of days are not showing under days textbox.(Done)
 2. Company dropdown- keydown is not working (after selecting the company using keyboard the address is not fetching in to the text box. (Done) NOT WORKING CORRECTLY.
3.City - Textbox Only (Removed)
4. Emai and spl instrustions are not mandatory.(Done) 
5. Room Tariff- different tariff details are showing. (Done)
6.Advance popup- User name should be removed. (Done)
7. After saving the data textboxs are not clearing. (Done)
8. Need to add clear button (Done)
9. Under DB Insert date is not updating. (Done) THREE INSERTIONS HAPPENED FOR ONE CLICK.
10. Reservation receipt is not showing after completing the advance inputting work. (Done)  NOT COMPLETED. 
11. Modify option is not working. (Done) - NO NEED OF ADVANCE POPUP
12. Need to work on Canceling of Reservation (Cancel button). NOT COMPLETED
**13.** ID Proof- Validation).**

**Comment by saikrishna20** [comment]
7.Data getting inserted into database only once checked with parameter values
8.Report gets directly printed after filling the advance details but takes time to print the receipt (Checked with parameter values)
9.Modify option changes made and removed advance popup for modification.
13.Validation for all the id proofs done and added dashes for aadhar card number and will appear automatically

**Comment by VelsolHMS** [comment]
Modiy option is not working, Please look into this. Check each and every functionality on this page

**Comment by saikrishna20** [comment]
Modify option working and all functionality checked.
