### ISSUE TITLE
Department Definition

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#10]
T-1 @SRIKARTHATI 
1. Add Button is not working. (DONE) 
Not saving. (DONE)
Error:
Additional information: Incorrect syntax near ','. (DONE)

**Comment by VelsolHMS** [comment]
After clicking on "Save" - "Add" and "Modify" buttons should enable and remaining should disable.

**Comment by SRIKARTHATI** [comment]
issue resloved

**Comment by VelsolHMS** [comment]
Done
