### ISSUE TITLE
Room Tax Definition

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#11]
T-1 @saikrishna20 
1. Factor - Error content should change. (Done)
2. status set as "Active" - selectindex. (Done)
Not saving to db. 
Additional information: Invalid column name 'USER_NAME'. (Done)
There are more columns in the INSERT statement than values specified in the VALUES clause. The number of values in the VALUES clause must match the number of columns specified in the INSERT statement.

**Comment by saikrishna20** [comment]
Factor content changed
Status set to active by default
Invalid column name error solved

**Comment by saikrishna20** [comment]
Mouse over issue resolved and need to push

**Comment by VelsolHMS** [comment]
Done
