### ISSUE TITLE
Aminities

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#12]
T-1 @saikrishna20 

1. Status - should be "Active" by default. (Done) - STILL IT IS SHOWING "INACTIVE" AFTER CLICKING "ADD" BUTTON
Not saving- error: 
Additional information: Conversion failed when converting date and/or time from character string.(Done)

**Comment by VelsolHMS** [comment]
1. Status - should be "Active" by default. (Done) - STILL IT IS SHOWING "INACTIVE" AFTER CLICKING "ADD" BUTTON

**Comment by saikrishna20** [comment]
Work completed status was set to Active and date time conversion failed error was resolved

**Comment by VelsolHMS** [comment]
Need to check with Modify option and list view is displaying when Modify button is clicked and list view is not fully functionable

**Comment by saikrishna20** [comment]
Modify option checked and data can be selected from the list view and based on the selection the data will be fetched for any changes and updates can be done.

**Comment by VelsolHMS** [comment]
Done
