### ISSUE TITLE
Enquiry

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#13]
T-1 

1. Time should be Automatically be 00:00 if they didn't input.  == (completed)
2. Search: from date  and to date are not working. ==(completed)
3. By Name and Contact is also not working.  == (completed)
4. Need to add Clear button for grid view.  ==(completed)
5. Set the Grid view and Textbox width.   #==(completed)
6. Vaidations: Name, Contact, Coming from (mandatory), Expected Room, Expected Type, Expected Arraival, Time are mandatory.  ==(completed)
7. Water Mark for TextBoxes == (completed)

**Comment by VelsolHMS** [comment]
1.Time should be Automatically be 00:00 if they didn't input. 
2. Search: from date and to date are not working
3. Date columns are duplicating.
4. When clearing errors are not getting clear.

**Comment by VelsolHMS** [comment]
Completed

**Comment by VelsolHMS** [comment]
Error when saving: Additional information: Conversion failed when converting date and/or time from character string.

**Comment by SRIKARTHATI** [comment]
completed change the system time(yyyy/mm/dd) check

**Comment by VelsolHMS** [comment]
Done
