### ISSUE TITLE
Post Charges

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#16]
T-1

"1. Not saving into database.  Error: 
Additional information: SqlDateTime overflow. Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM."

**Comment by saimanisha** [comment]
the above error occurs due to invalid datetime ."Must be between 1/1/1753 12:00:00 AM and 12/31/9999 11:59:59 PM." but here the date is given before the limit  which is not valid date year month.in such cases we face this kind of errors

**Comment by VelsolHMS** [comment]
Done

**Comment by VelsolHMS** [comment]
After clicking the button of roomno, data which is dynamically getting should not be editable, Keep text box as non editable.
Total Amount is not updating after entering data in charges textbox.

**Comment by saimanisha** [comment]
when we apply charges immediately the amount will appear as total amount .
