### ISSUE TITLE
Paidouts

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#17]
T-1
1. Opening balance - Error when saving (Invalid object name Paidout_openingbalance). 
2. Need to add Insert Date, Insert by, Update Date, Update by.

**Comment by saimanisha** [comment]
Error when  saving (Invalid object name Paidout_openingbalance) ITS DUE TO no such table name exists  in database and above columns were added in database of table PAIDOUT_OPENINGBALANS .

**Comment by VelsolHMS** [comment]
Add clear button, need to work on Modify functionality. Voucher number is not updating.

**Comment by VelsolHMS** [comment]
Need to create "Add" button

**Comment by saimanisha** [comment]
add and clear  buttons are added .voucher number is working

**Comment by VelsolHMS** [comment]
Done
