### ISSUE TITLE
Miscellenous Sales

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#18]
T-1

1. Need to  work on dropdowns.  
2. Need to work on Insert date, insert by, update date, update by.  ==(completed)
3. Unable to save, Error: Additional information: Incorrect syntax near ','.  ==(completed)
4. Need to Work on Receipt No.  ==(completed)
5. Currency Code should be in drop down. == (completed)

**Comment by SRIKARTHATI** [comment]
i didn't undurstand dropdown working

**Comment by VelsolHMS** [comment]
Need to Remove Modify from Mis.
