### ISSUE TITLE
login page

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#19]
1. Without user name, password signing is working.   ===(COMPLETED)
2. If the username / password is wrong the cursor should be at same position. == (COMPLETED)
3. Placeholder on password and text should be password type.  == (COMPLETED)

**Comment by SRIKARTHATI** [comment]
USERNAME OR PASSWORD IS INNCORRECT ITS CLEAR AUTOMATICALLY

**Comment by VelsolHMS** [comment]
Done
