### ISSUE TITLE
CheckIn 

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#2]
T-1 Check in page Error @SRIKARTHATI 
1. Image is not displaying after uploading .(Done)
 2. Country - DropDown. (Done)
3. ID Proof Validation (PENDING)
4.Not saving into DB (No error).(Done) 
5. Need to add "Clear" button.(Done)
 6. Need to show a popup that if they added advance like "DO YOU WANT TO POST ADVANCE?" if OK Advance popup should come.(Done)
7.company dropdown                                     (done)

**Comment by VelsolHMS** [comment]
1. ID Proof Validation.

**Comment by SRIKARTHATI** [comment]
completed

**Comment by VelsolHMS** [comment]
Done

**Comment by VelsolHMS** [comment]
Unable to give a value at Pax, Error. Check it.

**Comment by VelsolHMS** [comment]
After the complete form filling, on the popup rename the cancel button text as "No" and if the "No" button is clicked, data should be saved and all the text fields should be clear.

**Comment by SRIKARTHATI** [comment]
popup alignment AND object reference error was resloved ,change the cheque_no datatype sql server 
completed

**Comment by VelsolHMS** [comment]
Done

**Comment by VelsolHMS** [comment]
Plan tariff is not showing in text boxes, Rack Tariff text boxes should be not editable and Charged tariff should be editable. Tax code is not displaying, by default it is showing "0".

**Comment by SRIKARTHATI** [comment]
completed

**Comment by VelsolHMS** [comment]
Not saving into database ERROR

**Comment by SRIKARTHATI** [comment]
completed

**Comment by VelsolHMS** [comment]
Advance popup error, after saving data into it data is not saving.

**Comment by SRIKARTHATI** [comment]
completed check with new database
