### ISSUE TITLE
Advance

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#20]
1. Receipt No should be Primary key of Advance table.   ==(completed)

2. After selecting "Paymode" - text boxes should work. Check with Amount Received / Particulars text box.

==(completed)
3. Under database Advance for is showing Null - It should show Room / Reservation.  =(completed)

**Comment by SRIKARTHATI** [comment]
receipt number was advance primary key and paymnet mode resloved
completed

**Comment by VelsolHMS** [comment]
Done
