### ISSUE TITLE
Entire Room Page

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#23]
The number of vancant rooms , occupied rooms on the home page are increment every time.

**Comment by saimanisha** [comment]
issue is resolved now every time on loading this page it starts from zero and never increments.

**Comment by VelsolHMS** [comment]
Done, Good Job

**Comment by VelsolHMS** [comment]
Check with the Entire Room page button color changing functionality. If room trasferred the source room button color should be change to "Dirty" color, even if the room is checkout same and even if the room changes from Maintanence or management. after dirty it should change automatically to vacant after 10mins.
