### ISSUE TITLE
Departure CheckIn

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#24]
T-1
1. Without giving any value if we submit/ save - Page is navigating to Vacant Room page.
Need to restrict that.

**Comment by VelsolHMS** [comment]
Make the Textbox of time as non-editable.

**Comment by saimanisha** [comment]
time field is now uneditable

**Comment by VelsolHMS** [comment]
Done

**Comment by VelsolHMS** [comment]
Need to Restrict the "OK" button. without giving any data in the text fields page in navigating to Vacant room page.

**Comment by saimanisha** [comment]
when  either of these time and date textboxes are not filled then it never navigates to vacant page.

**Comment by VelsolHMS** [comment]
Done
