### ISSUE TITLE
Checkout

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#26]
T-1
Need to work on checkout - 
1. Once the we click on room no in checkout page data should be filled in two grid views, in first Grid View - all the details should come and on second one guest details , arrival date, Departure date should come.
2. If we click on any column of first grid view complete data should be shown in date wise.
3. Once the Print bill button is clicked bill number should be generate for the check-in and output should be come (print)
4. And the room no / button of the room number should be clear from checkout page.
5. Prov bill - Sample bill here no bill number will generate.
6.View Bill - Just a bill of pdf will shown.
5. After the  "Settle bill" functionality will be there. first complete the above things and then after I will tell about other things.

**Comment by saikrishna20** [comment]
Functionality completed need to test
