### ISSUE TITLE
Room Master

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#4]
T-1 @SRIKARTHATI 

1. Need to decrease fontsize of Amenities. ==(completed) 
2.Room category - Dropdown should work with tab. == (completed)
 3.Room View - AlphaNumeric with space. == (completed)
 4. Set plan code dropdown default text as "Select a Plan". ===()
5. Common tariff textbox only work when it is 4+ pax.  ==(completed)
6.After the data come to gridview, room view validation error is displaying. 
Modify ==(completed) 
7. When entering room number active from date error is showing. ==(completed) 
Error: Column "Active_Calender doesnot belong to table". == (completed)

**Comment by SRIKARTHATI** [comment]
in combobox we apply the "select a plan" it will show error because plan code comes defalut on dropdown 

and other issues are resloved

**Comment by VelsolHMS** [comment]
1. Categories are not showing on dropdown.
2. Data can't save when modifying.
3. When selecting the Roomno from Dropdown error is displaying.

**Comment by SRIKARTHATI** [comment]
after search button click confirm button then click save it shpould work

**Comment by VelsolHMS** [comment]
All bugs are rectified and need to work on other things we will talk on this on T-2 test

**Comment by VelsolHMS** [comment]
Need to check with the Room master Plan code functionality. 
Check the DB of RoomMaster_plan table under this plan code is not showing. 
Under modify functionality plans are not displaying.
For common plan data is not saving in DB.(for example if we have 4+ rooms common plan will enable and if we confirming data is getting to datagrid.

**Comment by VelsolHMS** [comment]
After saving , the data on text boxes are not clearing from it.

**Comment by saimanisha** [comment]
completed
