### ISSUE TITLE
Company Master

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#5]
T-1 @saikrishna20 
1. LandMark- 25 characters. 
2. Country - Dropdown. 
3.Remarks- Optional 
4.Status: It should be active when page loads set (selected index = 0) 
5. Not saving to db. 
Error: Implicit converstion from datatype nvarchar to binary is not allowed. Use the "Conver" function to run this query.

**Comment by saikrishna20** [comment]
Issues resolved : 
1.Landmark is accepting only 25 characters.
2.Country was set to drop down with default values (India & USA)
3.Remarks is set to optional
4.Status was set to active when page loads
5.Conversion failed error was resolved and data is getting saved into DB checked with parameter values

**Comment by VelsolHMS** [comment]
Need to commit

**Comment by VelsolHMS** [comment]
T-1

1. City text box.

 Error when saving data: Implicit conversion from data type nvarchar to binary is not allowed. Use the CONVERT function to run this query.

**Comment by saikrishna20** [comment]
1. Combobox removed and changed to textbox or city.
2.Data is getting saved

**Comment by VelsolHMS** [comment]
Need to work with data fetching through Company code and name

**Comment by VelsolHMS** [comment]
COMPLETED

**Comment by VelsolHMS** [comment]
Error when saving without Credit limit data. check with full functionality

**Comment by VelsolHMS** [comment]
Not working check once again
