### ISSUE TITLE
Room category

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#6]
T-1 @SRIKARTHATI 
1. Button save text should be like "Save". (DONE)
2. Not saving the data into db.  (DONE)
Error: Conversion failed when converting date and/or time from character string. (DONE)

**Comment by VelsolHMS** [comment]
Need to check with buttons (Enable and Disable) and modify option is not working. If we select Active button to future date till that time the category should not display any where (ex: Room Tariff Master).

**Comment by SRIKARTHATI** [comment]
buttons issue resloved 
activedate pending

**Comment by SRIKARTHATI** [comment]
Active Date resloved

**Comment by VelsolHMS** [comment]
Completed.
