### ISSUE TITLE
Plan code Definition

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#7]
T-1 @saikrishna20 
1. Plan name should accept space.
 2. Not saving the data into db.  

Error: Conversion failed when converting date and/or time from character string.

**Comment by saikrishna20** [comment]
Issues resolved : 
Plane name is accepting spaces
data is getting saved into DB (checked with values)

**Comment by VelsolHMS** [comment]
Need to commit changes

**Comment by VelsolHMS** [comment]
Done. Completed. Need to work with other version
