### ISSUE TITLE
Registration Form

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#8]
T-1 @SRIKARTHATI 

1. Modify button functionality is not implemented.(done)
 2.User textbox should be searchable. ==(completed)

**Comment by SRIKARTHATI** [comment]
searchable shouldpending but it will modify(update ) in last focus method = resloved

**Comment by VelsolHMS** [comment]
Done

**Comment by VelsolHMS** [comment]
When modifying the data, it is inserting in db where it should update.
