### ISSUE TITLE
Revenue code Definition

### ISSUE THREAD

**Issue by VelsolHMS** [Velsolopc/VelRooms#9]
T-1 @saikrishna20 

1. Mis, Print, Status- should show by default Active and no. (Done)
2.Remove - Date and time (Done)
3. Save Error- Additional information: Conversion failed when converting date and/or time from character string. (Done)

**Comment by saikrishna20** [comment]
completed mis,print set to no by default and status set to active , date time removed, conversion failed error was resolved

**Comment by VelsolHMS** [comment]
Done . But check with the update Date and Update by in db

**Comment by saikrishna20** [comment]
Update date and by is assigned to srikar

**Comment by VelsolHMS** [comment]
Done
